name: build-wstunnel-mt7628

"on":
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rust-cross/rust-musl-cross:mipsel-musl
    steps:
      - name: Checkout wstunnel source
        uses: actions/checkout@v4
        with:
          repository: 'erebe/wstunnel'
          ref: 'main'

      - name: Fetch dependencies
        run: |
          cargo fetch

      - name: Patch kio
        run: |
          KIO_DIR=$(find /root/.cargo/registry/src -type d -name "kio-*" | head -1)
          sed -i 's/AtomicU64/AtomicUsize/g; s/u64/usize/g' "$KIO_DIR/src/waiter.rs"

      - name: Build
        env:
          RUSTFLAGS: "-C target-feature=+crt-static"
        run: |
          cargo build --target mipsel-unknown-linux-musl --release --config 'profile.release.panic="unwind"'

      - name: Package
        run: |
          mkdir -p output
          cp target/mipsel-unknown-linux-musl/release/wstunnel output/
          cd output
          tar -czf wstunnel_mt7628.tar.gz wstunnel

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: wstunnel-mt7628-bin
          path: output/*.tar.gz   
